# {
  "swarm": {
    # swarm_n: 4
    "1": {
      "model": "x500",
      "initial_pose": {
        "x": 0.0,
        "y": 1.0
      },
      "is_leader": true
    },
    "2": {
      "model": "x500",
      "initial_pose": {
        "x": 1.0,
        "y": 0.0
      },
      "is_leader": false
    },
    "3": {
      "model": "x500",
      "initial_pose": {
        "x": 3.0,
        "y": 0.0
      },
      "is_leader": false
    },
    "4": {
      "model": "x500",
      "initial_pose": {
        "x": 1.0,
        "y": 1.0
      },
      "is_leader": false
    }
  }
  # "trajectory": "waypoints_up_and_down.yaml"
# }
